openapi: 3.1.0
info:
  title: Mobile Authentication API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/v1/auth/generate-otp:
    post:
      summary: Generate OTP for mobile number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_number:
                  type: string
                  example: "1234567890"
      responses:
        "200":
          description: OTP generated successfully
        "500":
          description: Internal server error
  /api/v1/auth/verify-otp:
    post:
      summary: Verify OTP and generate JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile_number:
                  type: string
                  example: "1234567890"
                otp:
                  type: string
                  example: "1234"
      responses:
        "200":
          description: OTP verified 
        "400":
          description: Invalid or expired OTP
        "500":
          description: Internal server error
